//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLWebSide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ladder
    {
        public int LadderID { get; set; }
        public int ClubID { get; set; }
        public int TeamName { get; set; }
        public int Position { get; set; }
        public int Played { get; set; }
        public int Points { get; set; }
        public int Win { get; set; }
        public int Draw { get; set; }
        public int Lost { get; set; }
        public int Byes { get; set; }
        public int For { get; set; }
        public int Against { get; set; }
        public int Diff { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
