//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRL_WebSide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string TeamName { get; set; }
        public string Position { get; set; }
        public int ClubID { get; set; }
        public string Stats { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
